# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: 'browser name'
        default: 'chrome'
      testname:
        description: 'enter the regex to run the tests'
        type: string
      xmlsname:
        type: string
        description: 'enter on or multiple xmls to run'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: run test with xml files
        if: ${{inputs.xmlsname}}
        run: >
          mvn clean test
          -Dsurefire.suiteXmlFile=${{inputs.xmlsname}}
          -DenableBrowserOptions=true -Dmaven.test.failure.ignore=true
      - name: run specific tests with regex
        if: ${{inputs.testname}}
        run: >
          mvn clean test
          -Dtest=${{inputs.testname}}
          -Dbrowser=${{inputs.browsername}}
          -DenableBrowserOptions=true -Dmaven.test.failure.ignore=true
      - name: archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: sparkHtml
          path: ./reports/*.html
